compile: helloWorld.c multiplyMatrices.c
	gcc -o helloWorld helloWorld.c -lm -O3 -lpthread
	gcc -o multiplyMatrices multiplyMatrices.c -lm -O3 -lpthread
	gcc -o multiplyMatricesStrassen multiplyMatricesStrassen.c -lm -O3 -lpthread
	gcc -o home1 home1.c -lm -O3 -lpthread
	gcc -o home2 home2.c -lm -O3 -lpthread
clean:
	rm helloWorld multiplyMatrices multiplyMatricesStrassen home1 home2
