build:
	gcc -o bubbleSort bubbleSort.c -lm -O3 -lpthread
	gcc -o helloWorld helloWorld.c -lm -O3 -lpthread
	gcc -o mergeSort mergeSort.c -lm -O3 -lpthread
	gcc -o rowColumnSort rowColumnSort.c -lm -O3 -lpthread
	gcc -o rowColumnSortParallel rowColumnSortParallel.c -lm -O3 -lpthread
clean:
	rm mergeSort helloWorld bubbleSort
